version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binaries:
      - jv
    ldflags: "-s -w"

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - id: jv_deb
    package_id: jv
    bindir: /usr/local/bin
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}.deb"
    formats:
      - deb
    dependencies:
      - libc6
    contents:
      - src: ./README.md
        dst: /usr/share/doc/jv/README.md
    maintainer: "Your Name <your.email@example.com>"
    vendor: "Your Organization"
    license: "MIT"
    homepage: "https://github.com/vndr/jv"
    description: "JV IP Tool is a command-line tool for fetching IP addresses."

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
