# .github/workflows/go-tests.yml
name: Go Unit Tests

on:
    pull_request:
      branches:
        - main
        - develop
        - release/*

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # Updated to the latest version
      - name: Set up Go
        uses: actions/setup-go@v4  # Updated to the latest version
        with:
          go-version: '1.22'

      - name: Run tests
        run: go test ./... -v
