name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch: 

jobs:
  release:
    runs-on: self-hosted
        
    env:
      GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Install Goreleaser
        run: |
          curl -sfL https://goreleaser.com/static/run | bash

      - name: Run Goreleaser
        run: goreleaser release
