name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Install Goreleaser
        run: |
          curl -sfL https://goreleaser.com/static/run | bash VERSION=v2.2.0 -s -- check

      - name: Run Goreleaser
        run: goreleaser release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
