name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch: # Allows manual triggering

jobs:
  release:
    runs-on: self-hosted

    env:
      GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }} # Set the token for all steps

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for all tags and branches

      - name: Show Git history
        run: git log --oneline --decorate

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Install GoReleaser via apt
        run: |
          echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | sudo tee /etc/apt/sources.list.d/goreleaser.list
          sudo apt update
          sudo apt install -y goreleaser

      - name: Install nfpm
        run: |
          curl -sSL https://github.com/goreleaser/nfpm/releases/download/v2.12.1/nfpm_2.12.1_linux_amd64.deb -o nfpm.deb
          sudo dpkg -i nfpm.deb

      - name: Run GoReleaser
        run: goreleaser release --clean
