name: Release

on:
  push:
    tags:
      - "v*"  # Trigger on version tags
  workflow_dispatch: # Allows manual triggering

env:
  GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}  # Make GITHUB_TOKEN available for all jobs

jobs:
  release:
    runs-on: self-hosted
    outputs:
      version: ${{ steps.get_release.outputs.version }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for all tags and branches

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Install GoReleaser via apt
        run: |
          echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | sudo tee /etc/apt/sources.list.d/goreleaser.list
          sudo apt update
          sudo apt install -y goreleaser

      - name: Run GoReleaser
        run: goreleaser release --clean

      - name: Get Release Info
        id: get_release
        run: |
          VERSION=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
          echo "::set-output name=version::$VERSION"

  update-homebrew:
    needs: release
    runs-on: self-hosted

    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Clone the homebrew-jv repository into a separate directory
        run: |
          git clone https://github.com/vndr/homebrew-jv.git homebrew-jv-repo
          cd homebrew-jv-repo
          git checkout -b update-formula-${{ needs.release.outputs.version }}

      - name: Calculate SHA256 for Artifacts
        id: calculate_sha256
        run: |
          VERSION=${{ needs.release.outputs.version }}
          DARWIN_AMD64_URL="https://github.com/vndr/jv/releases/download/$VERSION/jv_Darwin_x86_64.tar.gz"
          DARWIN_ARM64_URL="https://github.com/vndr/jv/releases/download/$VERSION/jv_Darwin_arm64.tar.gz"
          LINUX_AMD64_URL="https://github.com/vndr/jv/releases/download/$VERSION/jv_Linux_x86_64.tar.gz"
          LINUX_ARM64_URL="https://github.com/vndr/jv/releases/download/$VERSION/jv_Linux_arm64.tar.gz"

          DARWIN_AMD64_SHA256=$(curl -Ls $DARWIN_AMD64_URL | sha256sum | awk '{print $1}')
          DARWIN_ARM64_SHA256=$(curl -Ls $DARWIN_ARM64_URL | sha256sum | awk '{print $1}')
          LINUX_AMD64_SHA256=$(curl -Ls $LINUX_AMD64_URL | sha256sum | awk '{print $1}')
          LINUX_ARM64_SHA256=$(curl -Ls $LINUX_ARM64_URL | sha256sum | awk '{print $1}')

          echo "::set-output name=darwin_amd64_sha256::$DARWIN_AMD64_SHA256"
          echo "::set-output name=darwin_arm64_sha256::$DARWIN_ARM64_SHA256"
          echo "::set-output name=linux_amd64_sha256::$LINUX_AMD64_SHA256"
          echo "::set-output name=linux_arm64_sha256::$LINUX_ARM64_SHA256"

      - name: Configure Git User
        run: |
          git config --global user.email "info@vndr.net"
          git config --global user.name "vndr"

      - name: Update Homebrew Formula
        run: |
          cd homebrew-jv-repo
          FORMULA_PATH="jv.rb"

          # Update version, URLs, and SHA256 in the formula
          sed -i "s|url \".*Darwin_x86_64.tar.gz\"|url \"https://github.com/vndr/jv/releases/download/${{ needs.release.outputs.version }}/jv_Darwin_x86_64.tar.gz\"|" $FORMULA_PATH
          sed -i "s|sha256 \".*\"|sha256 \"${{ steps.calculate_sha256.outputs.darwin_amd64_sha256 }}\"|" $FORMULA_PATH

          sed -i "s|url \".*Darwin_arm64.tar.gz\"|url \"https://github.com/vndr/jv/releases/download/${{ needs.release.outputs.version }}/jv_Darwin_arm64.tar.gz\"|" $FORMULA_PATH
          sed -i "s|sha256 \".*\"|sha256 \"${{ steps.calculate_sha256.outputs.darwin_arm64_sha256 }}\"|" $FORMULA_PATH

          sed -i "s|url \".*Linux_x86_64.tar.gz\"|url \"https://github.com/vndr/jv/releases/download/${{ needs.release.outputs.version }}/jv_Linux_x86_64.tar.gz\"|" $FORMULA_PATH
          sed -i "s|sha256 \".*\"|sha256 \"${{ steps.calculate_sha256.outputs.linux_amd64_sha256 }}\"|" $FORMULA_PATH

          sed -i "s|url \".*Linux_arm64.tar.gz\"|url \"https://github.com/vndr/jv/releases/download/${{ needs.release.outputs.version }}/jv_Linux_arm64.tar.gz\"|" $FORMULA_PATH
          sed -i "s|sha256 \".*\"|sha256 \"${{ steps.calculate_sha256.outputs.linux_arm64_sha256 }}\"|" $FORMULA_PATH

          # Update the version field
          sed -i "s/version \".*\"/version \"${{ needs.release.outputs.version }}\"/" $FORMULA_PATH

      - name: Commit and Push Changes
        run: |
          cd homebrew-jv-repo
          git remote set-url origin https://x-access-token:${{ secrets.RELEASE_TOKEN }}@github.com/vndr/homebrew-jv.git
          git add jv.rb
          git commit -m "Update JV formula to version ${{ needs.release.outputs.version }}"
          git push origin update-formula-${{ needs.release.outputs.version }}

      - name: Create Pull Request
        run: |
          cd homebrew-jv-repo
          gh pr create --title "Update JV formula to version ${{ needs.release.outputs.version }}" \
                       --body "This PR updates the JV formula to version ${{ needs.release.outputs.version }} with the correct download URLs and SHA256 checksums." \
                       --base main --head update-formula-${{ needs.release.outputs.version }}
